export const UPDATE_POSTS = "UPDATE_POSTS";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const LOG_OUT = "LOG_OUT";

export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const CLEAR_ERRORRR = "CLEAR_ERRORRR";

export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAILED = "EDIT_USER_FAILED";

export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";
export const FETCH_USER_START = "FETCH_USER_START";

export const FETCH_FRIENDS = "FETCH_FRIENDS";

export const ADD_FRIENDS = 'ADD_FRIENDS'
export const REMOVE_FRIENDS = 'REMOVE_FRIENDS'

export const CREATE_POST = 'CREATE_POST'
export const CREATE_COMMENT = 'CREATE_COMMENT'

export const UPDATE_POST_LIKE = 'UPDATE_POST_LIKE'

export const FETCH_USER_FROM_SEARCH = 'FETCH_USER_FROM_SEARCH'



